#%RAML 1.0
title: uhub-sapi
baseUri: http://localhost:8081/covid/v1
securitySchemes:
  oauth2.0: !include /exchange_modules/a747e3ce-6f9e-4bf3-9208-d6e23369b012/uho-oauth-20-security-scheme/1.0.0/uho-oauth-20-security-scheme.raml
traits:
  correlation-id-header: !include /exchange_modules/a747e3ce-6f9e-4bf3-9208-d6e23369b012/x-correlation-id-header/1.0.0/x-correlation-id-header.raml
  transaction-id-header: !include /exchange_modules/a747e3ce-6f9e-4bf3-9208-d6e23369b012/x-transaction-id-header/1.0.0/x-transaction-id-header.raml
  covid-reports-query-param: !include /traits/covid-reports-query-param.raml
uses:
  uhub-sapi-data-types: uhub-sapi-datatypes-library/uhub-sapi-datatypes-library.raml
  uhub-sapi-xml-error-response: uhub-sapi-datatypes-library/error-response-xml-type.raml
  uho-common-data-types: /exchange_modules/a747e3ce-6f9e-4bf3-9208-d6e23369b012/uho-common-data-types-library/1.0.0/uho-common-data-types-library.raml

/cases:
  post:
    description: This resource used to register a covid case.
    is: [correlation-id-header, transaction-id-header]
    body:
      application/json:
        type: uhub-sapi-data-types.register-covid-case-request-type
        example: !include examples/register-covid-case-request-payload.json
    responses:
        200:
           body:
              application/json:
                  type: uhub-sapi-data-types.register-covid-case-response-type
                  example: !include examples/register-covid-case-response-payload.json          
        400:
          body:
            application/json:
              type: uho-common-data-types.error-response-type
              example: !include examples/400.json          
        503:
          body:
            application/json:
              type: uho-common-data-types.error-response-type
              example: !include examples/503.json        
        500:
          body:
            application/json:
              type: uho-common-data-types.error-response-type
              example: !include examples/500.json             
  put:
    description: This resource used to update a covid case.
    is: [correlation-id-header, transaction-id-header]
    body:
      application/xml:
        type: uhub-sapi-data-types.update-covid-case-request-type
        example: !include examples/update-covid-case-request-payload.xml
    responses:
      200:
        body:
          application/xml:
            type: 
              type: uhub-sapi-data-types.update-covid-case-response-type
              example: !include examples/update-covid-case-response-payload.xml           
      400:
        body:
          application/xml: 
                type: uhub-sapi-xml-error-response.response
                example: !include examples/400.xml         
      503:
        body:
          application/xml:
                type: uhub-sapi-xml-error-response.response
                example: !include examples/503.xml      
      500:
        body:
          application/xml:
                type: uhub-sapi-xml-error-response.response
                example: !include examples/500.xml    
  /{nationalID}:
    get:
      description: To get covid cases by national id
      is: [correlation-id-header, transaction-id-header] 
      responses:
        200:
          body:
            application/json:
              type: uhub-sapi-data-types.get-cases-by-national-id-response-type
              example: !include examples/get-covid-case-by-national-response.json 
        503:
          body:
            application/json:
              type: uho-common-data-types.error-response-type
              example: !include examples/503.json       
        500:
          body:
            application/json:
              type: uho-common-data-types.error-response-type
              example: !include examples/500.json
/reports: 
  description: To get reports by state wise and if state not provided all states reports responded
  get:
    is: [correlation-id-header, transaction-id-header, covid-reports-query-param]
    responses:
      200:
        body:
          application/json:
            type: uhub-sapi-data-types.get-reports-response-type
            example: !include examples/get-covid-reports-response.json     
      503:
          body:
            application/json:
              type: uho-common-data-types.error-response-type
              example: !include examples/503.json        
      500:
          body:
            application/json:
              type: uho-common-data-types.error-response-type
              example: !include examples/500.json
/health-check:
  description: To check health status of API
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message": "Uhub-sapi is alive and kicking"
              }
     

      

        

  
  


            
                
              

        
